const json = {
    "fetchparadise3Response": {
        "Results": {
            "Result 1": {
                "Row": [
                    {
                        "paradisescore": 302,
                        "state": "NJ",
                        "statename": "New Jersey          ",
                        "pubcnt": "2571",
                        "prvcnt": "581",
                        "avestratio": 11.78,
                        "studentteacherscore": 46,
                        "prvschoolscore": 42,
                        "publicschoolscore": 45,
                        "violentcomprat": 0.1644,
                        "propcomprat": 1.3057,
                        "violentscore": 26,
                        "propcrimescore": 37,
                        "sumcum": -12.95,
                        "maxcum": -3.21,
                        "mincum": -23.18,
                        "mortalityscore": 44,
                        "evtsum": 23,
                        "injsum": 61,
                        "fatsum": 39,
                        "evtscore": 11,
                        "injscore": 29,
                        "fatscore": 22
                    },
                    {
                        "paradisescore": 298,
                        "state": "ME",
                        "statename": "Maine               ",
                        "pubcnt": "587",
                        "prvcnt": "92",
                        "avestratio": 10.7,
                        "studentteacherscore": 52,
                        "prvschoolscore": 14,
                        "publicschoolscore": 14,
                        "violentcomprat": 0.0586,
                        "propcomprat": 1.1054,
                        "violentscore": 51,
                        "propcrimescore": 45,
                        "sumcum": -2.3,
                        "maxcum": 15.11,
                        "mincum": -16.77,
                        "mortalityscore": 33,
                        "evtsum": 24,
                        "injsum": 14,
                        "fatsum": 7,
                        "evtscore": 10,
                        "injscore": 41,
                        "fatscore": 38
                    },
                    {
                        "paradisescore": 293,
                        "state": "VA",
                        "statename": "Virginia            ",
                        "pubcnt": "1967",
                        "prvcnt": "477",
                        "avestratio": 13.67,
                        "studentteacherscore": 30,
                        "prvschoolscore": 39,
                        "publicschoolscore": 39,
                        "violentcomprat": 0.1137,
                        "propcomprat": 1.1781,
                        "violentscore": 41,
                        "propcrimescore": 42,
                        "sumcum": -15.23,
                        "maxcum": -6.49,
                        "mincum": -24.81,
                        "mortalityscore": 46,
                        "evtsum": 26,
                        "injsum": 99,
                        "fatsum": 31,
                        "evtscore": 8,
                        "injscore": 22,
                        "fatscore": 26
                    },
                    {
                        "paradisescore": 291,
                        "state": "VT",
                        "statename": "Vermont             ",
                        "pubcnt": "298",
                        "prvcnt": "69",
                        "avestratio": 10.88,
                        "studentteacherscore": 50,
                        "prvschoolscore": 9,
                        "publicschoolscore": 7,
                        "violentcomprat": 0.0615,
                        "propcomprat": 1.1583,
                        "violentscore": 50,
                        "propcrimescore": 43,
                        "sumcum": -6.44,
                        "maxcum": 10.3,
                        "mincum": -20.76,
                        "mortalityscore": 39,
                        "evtsum": 22,
                        "injsum": 5,
                        "fatsum": 9,
                        "evtscore": 12,
                        "injscore": 45,
                        "fatscore": 36
                    },
                    {
                        "paradisescore": 287,
                        "state": "CT",
                        "statename": "Connecticut         ",
                        "pubcnt": "1049",
                        "prvcnt": "220",
                        "avestratio": 11.86,
                        "studentteacherscore": 43,
                        "prvschoolscore": 26,
                        "publicschoolscore": 24,
                        "violentcomprat": 0.137,
                        "propcomprat": 1.338,
                        "violentscore": 33,
                        "propcrimescore": 34,
                        "sumcum": -6.19,
                        "maxcum": 6.83,
                        "mincum": -18.75,
                        "mortalityscore": 38,
                        "evtsum": 24,
                        "injsum": 13,
                        "fatsum": 8,
                        "evtscore": 10,
                        "injscore": 42,
                        "fatscore": 37
                    },
                    {
                        "paradisescore": 284,
                        "state": "NH",
                        "statename": "New Hampshire       ",
                        "pubcnt": "511",
                        "prvcnt": "97",
                        "avestratio": 10.77,
                        "studentteacherscore": 51,
                        "prvschoolscore": 17,
                        "publicschoolscore": 13,
                        "violentcomprat": 0.0683,
                        "propcomprat": 0.9894,
                        "violentscore": 48,
                        "propcrimescore": 48,
                        "sumcum": 10.71,
                        "maxcum": 29.85,
                        "mincum": -5.96,
                        "mortalityscore": 15,
                        "evtsum": 20,
                        "injsum": 18,
                        "fatsum": 5,
                        "evtscore": 14,
                        "injscore": 39,
                        "fatscore": 39
                    },
                    {
                        "paradisescore": 284,
                        "state": "NY",
                        "statename": "New York            ",
                        "pubcnt": "4963",
                        "prvcnt": "1169",
                        "avestratio": 11.8,
                        "studentteacherscore": 45,
                        "prvschoolscore": 47,
                        "publicschoolscore": 51,
                        "violentcomprat": 0.2553,
                        "propcomprat": 1.3391,
                        "violentscore": 12,
                        "propcrimescore": 33,
                        "sumcum": -22.59,
                        "maxcum": -14.87,
                        "mincum": -31.29,
                        "mortalityscore": 48,
                        "evtsum": 33,
                        "injsum": 57,
                        "fatsum": 62,
                        "evtscore": 3,
                        "injscore": 31,
                        "fatscore": 14
                    },
                    {
                        "paradisescore": 279,
                        "state": "MA",
                        "statename": "Massachusetts       ",
                        "pubcnt": "1908",
                        "prvcnt": "430",
                        "avestratio": 11.45,
                        "studentteacherscore": 48,
                        "prvschoolscore": 35,
                        "publicschoolscore": 37,
                        "violentcomprat": 0.2267,
                        "propcomprat": 1.2463,
                        "violentscore": 17,
                        "propcrimescore": 40,
                        "sumcum": 7.25,
                        "maxcum": 21.77,
                        "mincum": -6.82,
                        "mortalityscore": 18,
                        "evtsum": 26,
                        "injsum": 27,
                        "fatsum": 5,
                        "evtscore": 8,
                        "injscore": 37,
                        "fatscore": 39
                    },
                    {
                        "paradisescore": 267,
                        "state": "ND",
                        "statename": "North Dakota        ",
                        "pubcnt": "496",
                        "prvcnt": "37",
                        "avestratio": 11.15,
                        "studentteacherscore": 49,
                        "prvschoolscore": 3,
                        "publicschoolscore": 12,
                        "violentcomprat": 0.0665,
                        "propcomprat": 0.9546,
                        "violentscore": 49,
                        "propcrimescore": 49,
                        "sumcum": 5.39,
                        "maxcum": 22.42,
                        "mincum": -11.45,
                        "mortalityscore": 21,
                        "evtsum": 21,
                        "injsum": 45,
                        "fatsum": 10,
                        "evtscore": 13,
                        "injscore": 36,
                        "fatscore": 35
                    },
                    {
                        "paradisescore": 261,
                        "state": "PA",
                        "statename": "Pennsylvania        ",
                        "pubcnt": "3026",
                        "prvcnt": "1335",
                        "avestratio": 14.03,
                        "studentteacherscore": 27,
                        "prvschoolscore": 48,
                        "publicschoolscore": 47,
                        "violentcomprat": 0.1532,
                        "propcomprat": 1.0377,
                        "violentscore": 30,
                        "propcrimescore": 47,
                        "sumcum": 5.94,
                        "maxcum": 15.94,
                        "mincum": -5.56,
                        "mortalityscore": 20,
                        "evtsum": 26,
                        "injsum": 181,
                        "fatsum": 41,
                        "evtscore": 8,
                        "injscore": 14,
                        "fatscore": 20
                    },
                    {
                        "paradisescore": 251,
                        "state": "MN",
                        "statename": "Minnesota           ",
                        "pubcnt": "2097",
                        "prvcnt": "349",
                        "avestratio": 15.99,
                        "studentteacherscore": 16,
                        "prvschoolscore": 32,
                        "publicschoolscore": 41,
                        "violentcomprat": 0.1123,
                        "propcomprat": 1.3304,
                        "violentscore": 42,
                        "propcrimescore": 35,
                        "sumcum": -0.82,
                        "maxcum": 11.64,
                        "mincum": -14.4,
                        "mortalityscore": 29,
                        "evtsum": 26,
                        "injsum": 92,
                        "fatsum": 37,
                        "evtscore": 8,
                        "injscore": 24,
                        "fatscore": 24
                    },
                    {
                        "paradisescore": 250,
                        "state": "RI",
                        "statename": "Rhode Island        ",
                        "pubcnt": "324",
                        "prvcnt": "64",
                        "avestratio": 12.91,
                        "studentteacherscore": 36,
                        "prvschoolscore": 6,
                        "publicschoolscore": 10,
                        "violentcomprat": 0.1326,
                        "propcomprat": 1.374,
                        "violentscore": 35,
                        "propcrimescore": 31,
                        "sumcum": -1.01,
                        "maxcum": 17.99,
                        "mincum": -17.04,
                        "mortalityscore": 30,
                        "evtsum": 15,
                        "injsum": 1,
                        "fatsum": 5,
                        "evtscore": 16,
                        "injscore": 47,
                        "fatscore": 39
                    },
                    {
                        "paradisescore": 238,
                        "state": "WI",
                        "statename": "Wisconsin           ",
                        "pubcnt": "2252",
                        "prvcnt": "640",
                        "avestratio": 14.74,
                        "studentteacherscore": 19,
                        "prvschoolscore": 43,
                        "publicschoolscore": 42,
                        "violentcomprat": 0.1052,
                        "propcomprat": 1.249,
                        "violentscore": 46,
                        "propcrimescore": 39,
                        "sumcum": 1.3,
                        "maxcum": 13.07,
                        "mincum": -11.35,
                        "mortalityscore": 25,
                        "evtsum": 29,
                        "injsum": 262,
                        "fatsum": 104,
                        "evtscore": 5,
                        "injscore": 10,
                        "fatscore": 9
                    },
                    {
                        "paradisescore": 237,
                        "state": "WV",
                        "statename": "West Virginia       ",
                        "pubcnt": "675",
                        "prvcnt": "74",
                        "avestratio": 13.35,
                        "studentteacherscore": 33,
                        "prvschoolscore": 10,
                        "publicschoolscore": 16,
                        "violentcomprat": 0.1118,
                        "propcomprat": 0.8993,
                        "violentscore": 43,
                        "propcrimescore": 51,
                        "sumcum": 35.86,
                        "maxcum": 51.63,
                        "mincum": 20.51,
                        "mortalityscore": 1,
                        "evtsum": 24,
                        "injsum": 19,
                        "fatsum": 10,
                        "evtscore": 10,
                        "injscore": 38,
                        "fatscore": 35
                    },
                    {
                        "paradisescore": 234,
                        "state": "NE",
                        "statename": "New England         ",
                        "pubcnt": "1031",
                        "prvcnt": "154",
                        "avestratio": 12.94,
                        "studentteacherscore": 35,
                        "prvschoolscore": 21,
                        "publicschoolscore": 23,
                        "violentcomprat": 0.1344,
                        "propcomprat": 1.34,
                        "violentscore": 34,
                        "propcrimescore": 32,
                        "sumcum": 13.24,
                        "maxcum": 29.53,
                        "mincum": -4.9,
                        "mortalityscore": 12,
                        "evtsum": 24,
                        "injsum": 52,
                        "fatsum": 17,
                        "evtscore": 10,
                        "injscore": 34,
                        "fatscore": 33
                    },
                    {
                        "paradisescore": 234,
                        "state": "SD",
                        "statename": "South Dakota        ",
                        "pubcnt": "656",
                        "prvcnt": "56",
                        "avestratio": 12.81,
                        "studentteacherscore": 39,
                        "prvschoolscore": 5,
                        "publicschoolscore": 15,
                        "violentcomprat": 0.1079,
                        "propcomprat": 0.9127,
                        "violentscore": 45,
                        "propcrimescore": 50,
                        "sumcum": 2.78,
                        "maxcum": 18.28,
                        "mincum": -13.55,
                        "mortalityscore": 24,
                        "evtsum": 25,
                        "injsum": 88,
                        "fatsum": 40,
                        "evtscore": 9,
                        "injscore": 26,
                        "fatscore": 21
                    },
                    {
                        "paradisescore": 231,
                        "state": "MD",
                        "statename": "Maryland            ",
                        "pubcnt": "1449",
                        "prvcnt": "438",
                        "avestratio": 13.21,
                        "studentteacherscore": 34,
                        "prvschoolscore": 36,
                        "publicschoolscore": 33,
                        "violentcomprat": 0.2852,
                        "propcomprat": 1.5996,
                        "violentscore": 7,
                        "propcrimescore": 17,
                        "sumcum": -13.7,
                        "maxcum": -2.27,
                        "mincum": -24.79,
                        "mortalityscore": 45,
                        "evtsum": 24,
                        "injsum": 58,
                        "fatsum": 42,
                        "evtscore": 10,
                        "injscore": 30,
                        "fatscore": 19
                    },
                    {
                        "paradisescore": 227,
                        "state": "GA",
                        "statename": "Georgia             ",
                        "pubcnt": "2414",
                        "prvcnt": "457",
                        "avestratio": 13.8,
                        "studentteacherscore": 29,
                        "prvschoolscore": 38,
                        "publicschoolscore": 44,
                        "violentcomprat": 0.2056,
                        "propcomprat": 1.7025,
                        "violentscore": 22,
                        "propcrimescore": 11,
                        "sumcum": -6.47,
                        "maxcum": 2.89,
                        "mincum": -16.11,
                        "mortalityscore": 40,
                        "evtsum": 24,
                        "injsum": 168,
                        "fatsum": 43,
                        "evtscore": 10,
                        "injscore": 15,
                        "fatscore": 18
                    },
                    {
                        "paradisescore": 227,
                        "state": "MT",
                        "statename": "Montana             ",
                        "pubcnt": "717",
                        "prvcnt": "66",
                        "avestratio": 12.06,
                        "studentteacherscore": 42,
                        "prvschoolscore": 7,
                        "publicschoolscore": 18,
                        "violentcomprat": 0.1264,
                        "propcomprat": 1.3834,
                        "violentscore": 36,
                        "propcrimescore": 30,
                        "sumcum": 3.28,
                        "maxcum": 19.95,
                        "mincum": -12.84,
                        "mortalityscore": 23,
                        "evtsum": 26,
                        "injsum": 52,
                        "fatsum": 26,
                        "evtscore": 8,
                        "injscore": 34,
                        "fatscore": 29
                    },
                    {
                        "paradisescore": 227,
                        "state": "WY",
                        "statename": "Wyoming             ",
                        "pubcnt": "321",
                        "prvcnt": "17",
                        "avestratio": 11.51,
                        "studentteacherscore": 47,
                        "prvschoolscore": 1,
                        "publicschoolscore": 9,
                        "violentcomprat": 0.1232,
                        "propcomprat": 1.2691,
                        "violentscore": 38,
                        "propcrimescore": 38,
                        "sumcum": 9.52,
                        "maxcum": 27.97,
                        "mincum": -9.58,
                        "mortalityscore": 17,
                        "evtsum": 24,
                        "injsum": 51,
                        "fatsum": 20,
                        "evtscore": 10,
                        "injscore": 35,
                        "fatscore": 32
                    },
                    {
                        "paradisescore": 220,
                        "state": "NC",
                        "statename": "North Carolina      ",
                        "pubcnt": "2831",
                        "prvcnt": "427",
                        "avestratio": 14.36,
                        "studentteacherscore": 23,
                        "prvschoolscore": 34,
                        "publicschoolscore": 46,
                        "violentcomprat": 0.2002,
                        "propcomprat": 1.5685,
                        "violentscore": 23,
                        "propcrimescore": 20,
                        "sumcum": -5.57,
                        "maxcum": 3.41,
                        "mincum": -15.11,
                        "mortalityscore": 37,
                        "evtsum": 28,
                        "injsum": 94,
                        "fatsum": 112,
                        "evtscore": 6,
                        "injscore": 23,
                        "fatscore": 8
                    },
                    {
                        "paradisescore": 215,
                        "state": "IA",
                        "statename": "Iowa                ",
                        "pubcnt": "1387",
                        "prvcnt": "174",
                        "avestratio": 14.45,
                        "studentteacherscore": 21,
                        "prvschoolscore": 22,
                        "publicschoolscore": 30,
                        "violentcomprat": 0.1229,
                        "propcomprat": 1.2313,
                        "violentscore": 39,
                        "propcrimescore": 41,
                        "sumcum": 10.53,
                        "maxcum": 24.05,
                        "mincum": -3.83,
                        "mortalityscore": 16,
                        "evtsum": 23,
                        "injsum": 293,
                        "fatsum": 29,
                        "evtscore": 11,
                        "injscore": 8,
                        "fatscore": 27
                    },
                    {
                        "paradisescore": 213,
                        "state": "HI",
                        "statename": "Hawaii              ",
                        "pubcnt": "308",
                        "prvcnt": "91",
                        "avestratio": 14.23,
                        "studentteacherscore": 25,
                        "prvschoolscore": 13,
                        "publicschoolscore": 8,
                        "violentcomprat": 0.1044,
                        "propcomprat": 1.8996,
                        "violentscore": 47,
                        "propcrimescore": 4,
                        "sumcum": 0.02,
                        "maxcum": 33.52,
                        "mincum": -19.47,
                        "mortalityscore": 27,
                        "evtsum": 17,
                        "injsum": 15,
                        "fatsum": 12,
                        "evtscore": 15,
                        "injscore": 40,
                        "fatscore": 34
                    },
                    {
                        "paradisescore": 213,
                        "state": "OH",
                        "statename": "Ohio                ",
                        "pubcnt": "3557",
                        "prvcnt": "857",
                        "avestratio": 16.78,
                        "studentteacherscore": 10,
                        "prvschoolscore": 45,
                        "publicschoolscore": 49,
                        "violentcomprat": 0.1524,
                        "propcomprat": 1.4828,
                        "violentscore": 31,
                        "propcrimescore": 27,
                        "sumcum": 25.02,
                        "maxcum": 37.59,
                        "mincum": 11.27,
                        "mortalityscore": 7,
                        "evtsum": 24,
                        "injsum": 257,
                        "fatsum": 38,
                        "evtscore": 10,
                        "injscore": 11,
                        "fatscore": 23
                    },
                    {
                        "paradisescore": 210,
                        "state": "DE",
                        "statename": "Delaware            ",
                        "pubcnt": "234",
                        "prvcnt": "68",
                        "avestratio": 13.36,
                        "studentteacherscore": 32,
                        "prvschoolscore": 8,
                        "publicschoolscore": 5,
                        "violentcomprat": 0.2494,
                        "propcomprat": 1.5481,
                        "violentscore": 14,
                        "propcrimescore": 24,
                        "sumcum": 0.2,
                        "maxcum": 20.43,
                        "mincum": -16.12,
                        "mortalityscore": 26,
                        "evtsum": 15,
                        "injsum": 7,
                        "fatsum": 0,
                        "evtscore": 16,
                        "injscore": 44,
                        "fatscore": 41
                    },
                    {
                        "paradisescore": 208,
                        "state": "ID",
                        "statename": "Idaho               ",
                        "pubcnt": "750",
                        "prvcnt": "77",
                        "avestratio": 16.98,
                        "studentteacherscore": 9,
                        "prvschoolscore": 11,
                        "publicschoolscore": 19,
                        "violentcomprat": 0.1173,
                        "propcomprat": 1.1058,
                        "violentscore": 40,
                        "propcrimescore": 44,
                        "sumcum": 4.59,
                        "maxcum": 19.45,
                        "mincum": -10.71,
                        "mortalityscore": 22,
                        "evtsum": 28,
                        "injsum": 55,
                        "fatsum": 33,
                        "evtscore": 6,
                        "injscore": 32,
                        "fatscore": 25
                    },
                    {
                        "paradisescore": 207,
                        "state": "KS",
                        "statename": "Kansas              ",
                        "pubcnt": "1360",
                        "prvcnt": "153",
                        "avestratio": 13.21,
                        "studentteacherscore": 34,
                        "prvschoolscore": 20,
                        "publicschoolscore": 28,
                        "violentcomprat": 0.1777,
                        "propcomprat": 1.5486,
                        "violentscore": 24,
                        "propcrimescore": 23,
                        "sumcum": 17.53,
                        "maxcum": 32.84,
                        "mincum": 0.86,
                        "mortalityscore": 9,
                        "evtsum": 22,
                        "injsum": 72,
                        "fatsum": 25,
                        "evtscore": 12,
                        "injscore": 27,
                        "fatscore": 30
                    },
                    {
                        "paradisescore": 201,
                        "state": "MI",
                        "statename": "Michigan            ",
                        "pubcnt": "3459",
                        "prvcnt": "514",
                        "avestratio": 17.64,
                        "studentteacherscore": 5,
                        "prvschoolscore": 40,
                        "publicschoolscore": 48,
                        "violentcomprat": 0.2536,
                        "propcomprat": 1.5687,
                        "violentscore": 13,
                        "propcrimescore": 19,
                        "sumcum": 3.28,
                        "maxcum": 14.52,
                        "mincum": -9.15,
                        "mortalityscore": 23,
                        "evtsum": 25,
                        "injsum": 99,
                        "fatsum": 39,
                        "evtscore": 9,
                        "injscore": 22,
                        "fatscore": 22
                    },
                    {
                        "paradisescore": 200,
                        "state": "IN",
                        "statename": "Indiana             ",
                        "pubcnt": "1934",
                        "prvcnt": "549",
                        "avestratio": 15.77,
                        "studentteacherscore": 17,
                        "prvschoolscore": 41,
                        "publicschoolscore": 38,
                        "violentcomprat": 0.1615,
                        "propcomprat": 1.3873,
                        "violentscore": 27,
                        "propcrimescore": 29,
                        "sumcum": 26.02,
                        "maxcum": 39.38,
                        "mincum": 11.42,
                        "mortalityscore": 5,
                        "evtsum": 26,
                        "injsum": 115,
                        "fatsum": 56,
                        "evtscore": 8,
                        "injscore": 19,
                        "fatscore": 16
                    },
                    {
                        "paradisescore": 199,
                        "state": "IL",
                        "statename": "Illinois            ",
                        "pubcnt": "209",
                        "prvcnt": "819",
                        "avestratio": 12.33,
                        "studentteacherscore": 41,
                        "prvschoolscore": 44,
                        "publicschoolscore": 4,
                        "violentcomprat": 0.2665,
                        "propcomprat": 1.5008,
                        "violentscore": 11,
                        "propcrimescore": 26,
                        "sumcum": -4.27,
                        "maxcum": 6.21,
                        "mincum": -15.96,
                        "mortalityscore": 35,
                        "evtsum": 28,
                        "injsum": 122,
                        "fatsum": 60,
                        "evtscore": 6,
                        "injscore": 17,
                        "fatscore": 15
                    },
                    {
                        "paradisescore": 198,
                        "state": "AR",
                        "statename": "Arkansas            ",
                        "pubcnt": "1095",
                        "prvcnt": "94",
                        "avestratio": 12.82,
                        "studentteacherscore": 38,
                        "prvschoolscore": 15,
                        "publicschoolscore": 25,
                        "violentcomprat": 0.2188,
                        "propcomprat": 1.4823,
                        "violentscore": 21,
                        "propcrimescore": 28,
                        "sumcum": 27.19,
                        "maxcum": 42.48,
                        "mincum": 11.75,
                        "mortalityscore": 4,
                        "evtsum": 22,
                        "injsum": 92,
                        "fatsum": 22,
                        "evtscore": 12,
                        "injscore": 24,
                        "fatscore": 31
                    },
                    {
                        "paradisescore": 195,
                        "state": "CO",
                        "statename": "Colorado            ",
                        "pubcnt": "1990",
                        "prvcnt": "206",
                        "avestratio": 16.35,
                        "studentteacherscore": 13,
                        "prvschoolscore": 25,
                        "publicschoolscore": 40,
                        "violentcomprat": 0.1766,
                        "propcomprat": 1.6266,
                        "violentscore": 25,
                        "propcrimescore": 13,
                        "sumcum": -4.23,
                        "maxcum": 9.42,
                        "mincum": -19.57,
                        "mortalityscore": 34,
                        "evtsum": 27,
                        "injsum": 90,
                        "fatsum": 65,
                        "evtscore": 7,
                        "injscore": 25,
                        "fatscore": 13
                    },
                    {
                        "paradisescore": 195,
                        "state": "MO",
                        "statename": "Missouri            ",
                        "pubcnt": "2343",
                        "prvcnt": "441",
                        "avestratio": 12.79,
                        "studentteacherscore": 40,
                        "prvschoolscore": 37,
                        "publicschoolscore": 43,
                        "violentcomprat": 0.234,
                        "propcomprat": 1.5601,
                        "violentscore": 15,
                        "propcrimescore": 22,
                        "sumcum": 11.67,
                        "maxcum": 24.43,
                        "mincum": -2.36,
                        "mortalityscore": 13,
                        "evtsum": 24,
                        "injsum": 536,
                        "fatsum": 86,
                        "evtscore": 10,
                        "injscore": 3,
                        "fatscore": 12
                    },
                    {
                        "paradisescore": 191,
                        "state": "WA",
                        "statename": "Washington          ",
                        "pubcnt": "2252",
                        "prvcnt": "381",
                        "avestratio": 16.73,
                        "studentteacherscore": 11,
                        "prvschoolscore": 33,
                        "publicschoolscore": 42,
                        "violentcomprat": 0.1604,
                        "propcomprat": 1.8889,
                        "violentscore": 28,
                        "propcrimescore": 5,
                        "sumcum": -2.06,
                        "maxcum": 11.67,
                        "mincum": -15.34,
                        "mortalityscore": 31,
                        "evtsum": 33,
                        "injsum": 102,
                        "fatsum": 44,
                        "evtscore": 3,
                        "injscore": 21,
                        "fatscore": 17
                    },
                    {
                        "paradisescore": 184,
                        "state": "AK",
                        "statename": "Alaska              ",
                        "pubcnt": "459",
                        "prvcnt": "29",
                        "avestratio": 19.94,
                        "studentteacherscore": 3,
                        "prvschoolscore": 2,
                        "publicschoolscore": 11,
                        "violentcomprat": 0.299,
                        "propcomprat": 1.5898,
                        "violentscore": 6,
                        "propcrimescore": 18,
                        "sumcum": -17.42,
                        "maxcum": 17.83,
                        "mincum": -35.75,
                        "mortalityscore": 47,
                        "evtsum": 22,
                        "injsum": 3,
                        "fatsum": 5,
                        "evtscore": 12,
                        "injscore": 46,
                        "fatscore": 39
                    },
                    {
                        "paradisescore": 183,
                        "state": "KY",
                        "statename": "Kentucky            ",
                        "pubcnt": "1395",
                        "prvcnt": "226",
                        "avestratio": 16,
                        "studentteacherscore": 15,
                        "prvschoolscore": 28,
                        "publicschoolscore": 31,
                        "violentcomprat": 0.1255,
                        "propcomprat": 1.0699,
                        "violentscore": 37,
                        "propcrimescore": 46,
                        "sumcum": 24.32,
                        "maxcum": 37.69,
                        "mincum": 10.02,
                        "mortalityscore": 8,
                        "evtsum": 25,
                        "injsum": 708,
                        "fatsum": 164,
                        "evtscore": 9,
                        "injscore": 2,
                        "fatscore": 7
                    },
                    {
                        "paradisescore": 182,
                        "state": "CA",
                        "statename": "California          ",
                        "pubcnt": "9656",
                        "prvcnt": "1953",
                        "avestratio": 20.42,
                        "studentteacherscore": 1,
                        "prvschoolscore": 50,
                        "publicschoolscore": 53,
                        "violentcomprat": 0.2715,
                        "propcomprat": 1.6135,
                        "violentscore": 9,
                        "propcrimescore": 15,
                        "sumcum": -23.02,
                        "maxcum": -14.97,
                        "mincum": -32.06,
                        "mortalityscore": 49,
                        "evtsum": 37,
                        "injsum": 775,
                        "fatsum": 336,
                        "evtscore": 1,
                        "injscore": 1,
                        "fatscore": 3
                    },
                    {
                        "paradisescore": 182,
                        "state": "UT",
                        "statename": "Utah                ",
                        "pubcnt": "49",
                        "prvcnt": "92",
                        "avestratio": 14.25,
                        "studentteacherscore": 24,
                        "prvschoolscore": 14,
                        "publicschoolscore": 3,
                        "violentcomprat": 0.1111,
                        "propcomprat": 1.6155,
                        "violentscore": 44,
                        "propcrimescore": 14,
                        "sumcum": 11.19,
                        "maxcum": 28.12,
                        "mincum": -5.38,
                        "mortalityscore": 14,
                        "evtsum": 23,
                        "injsum": 69,
                        "fatsum": 25,
                        "evtscore": 11,
                        "injscore": 28,
                        "fatscore": 30
                    },
                    {
                        "paradisescore": 181,
                        "state": "FL",
                        "statename": "Florida             ",
                        "pubcnt": "3827",
                        "prvcnt": "1465",
                        "avestratio": 17.11,
                        "studentteacherscore": 8,
                        "prvschoolscore": 49,
                        "publicschoolscore": 50,
                        "violentcomprat": 0.3215,
                        "propcomprat": 1.9511,
                        "violentscore": 4,
                        "propcrimescore": 3,
                        "sumcum": -9.32,
                        "maxcum": -0.57,
                        "mincum": -18.27,
                        "mortalityscore": 42,
                        "evtsum": 27,
                        "injsum": 238,
                        "fatsum": 191,
                        "evtscore": 7,
                        "injscore": 12,
                        "fatscore": 6
                    },
                    {
                        "paradisescore": 179,
                        "state": "TX",
                        "statename": "Texas               ",
                        "pubcnt": "8987",
                        "prvcnt": "927",
                        "avestratio": 13.98,
                        "studentteacherscore": 28,
                        "prvschoolscore": 46,
                        "publicschoolscore": 52,
                        "violentcomprat": 0.2259,
                        "propcomprat": 1.8075,
                        "violentscore": 18,
                        "propcrimescore": 8,
                        "sumcum": 6.63,
                        "maxcum": 16.64,
                        "mincum": -5.59,
                        "mortalityscore": 19,
                        "evtsum": 34,
                        "injsum": 505,
                        "fatsum": 347,
                        "evtscore": 2,
                        "injscore": 4,
                        "fatscore": 2
                    },
                    {
                        "paradisescore": 175,
                        "state": "MS",
                        "statename": "Mississippi         ",
                        "pubcnt": "933",
                        "prvcnt": "128",
                        "avestratio": 14.13,
                        "studentteacherscore": 26,
                        "prvschoolscore": 19,
                        "publicschoolscore": 21,
                        "violentcomprat": 0.1383,
                        "propcomprat": 1.3179,
                        "violentscore": 32,
                        "propcrimescore": 36,
                        "sumcum": 28.09,
                        "maxcum": 43.07,
                        "mincum": 13.33,
                        "mortalityscore": 3,
                        "evtsum": 26,
                        "injsum": 264,
                        "fatsum": 40,
                        "evtscore": 8,
                        "injscore": 9,
                        "fatscore": 21
                    },
                    {
                        "paradisescore": 168,
                        "state": "OR",
                        "statename": "Oregon              ",
                        "pubcnt": "1301",
                        "prvcnt": "234",
                        "avestratio": 18.08,
                        "studentteacherscore": 4,
                        "prvschoolscore": 29,
                        "publicschoolscore": 27,
                        "violentcomprat": 0.1588,
                        "propcomprat": 1.8051,
                        "violentscore": 29,
                        "propcrimescore": 9,
                        "sumcum": -0.47,
                        "maxcum": 11.91,
                        "mincum": -12.92,
                        "mortalityscore": 28,
                        "evtsum": 30,
                        "injsum": 54,
                        "fatsum": 199,
                        "evtscore": 4,
                        "injscore": 33,
                        "fatscore": 5
                    },
                    {
                        "paradisescore": 164,
                        "state": "NM",
                        "statename": "New Mexico          ",
                        "pubcnt": "951",
                        "prvcnt": "96",
                        "avestratio": 13.61,
                        "studentteacherscore": 31,
                        "prvschoolscore": 16,
                        "publicschoolscore": 22,
                        "violentcomprat": 0.3294,
                        "propcomprat": 1.8654,
                        "violentscore": 2,
                        "propcrimescore": 6,
                        "sumcum": -4.69,
                        "maxcum": 8.83,
                        "mincum": -18.58,
                        "mortalityscore": 36,
                        "evtsum": 24,
                        "injsum": 199,
                        "fatsum": 28,
                        "evtscore": 10,
                        "injscore": 13,
                        "fatscore": 28
                    },
                    {
                        "paradisescore": 161,
                        "state": "SC",
                        "statename": "South Carolina      ",
                        "pubcnt": "1282",
                        "prvcnt": "204",
                        "avestratio": 14.38,
                        "studentteacherscore": 22,
                        "prvschoolscore": 24,
                        "publicschoolscore": 26,
                        "violentcomprat": 0.3268,
                        "propcomprat": 1.7082,
                        "violentscore": 3,
                        "propcrimescore": 10,
                        "sumcum": -2.18,
                        "maxcum": 8.08,
                        "mincum": -12.2,
                        "mortalityscore": 32,
                        "evtsum": 25,
                        "injsum": 145,
                        "fatsum": 42,
                        "evtscore": 9,
                        "injscore": 16,
                        "fatscore": 19
                    },
                    {
                        "paradisescore": 157,
                        "state": "AZ",
                        "statename": "Arizona             ",
                        "pubcnt": "1526",
                        "prvcnt": "201",
                        "avestratio": 16.58,
                        "studentteacherscore": 12,
                        "prvschoolscore": 23,
                        "publicschoolscore": 34,
                        "violentcomprat": 0.2275,
                        "propcomprat": 1.9667,
                        "violentscore": 16,
                        "propcrimescore": 2,
                        "sumcum": -11.43,
                        "maxcum": 1.03,
                        "mincum": -24.48,
                        "mortalityscore": 43,
                        "evtsum": 26,
                        "injsum": 121,
                        "fatsum": 879,
                        "evtscore": 8,
                        "injscore": 18,
                        "fatscore": 1
                    },
                    {
                        "paradisescore": 154,
                        "state": "AL",
                        "statename": "Alabama             ",
                        "pubcnt": "1405",
                        "prvcnt": "223",
                        "avestratio": 16.23,
                        "studentteacherscore": 14,
                        "prvschoolscore": 27,
                        "publicschoolscore": 32,
                        "violentcomprat": 0.2231,
                        "propcomprat": 1.5263,
                        "violentscore": 19,
                        "propcrimescore": 25,
                        "sumcum": 13.45,
                        "maxcum": 25.88,
                        "mincum": 0.85,
                        "mortalityscore": 11,
                        "evtsum": 27,
                        "injsum": 302,
                        "fatsum": 86,
                        "evtscore": 7,
                        "injscore": 7,
                        "fatscore": 12
                    },
                    {
                        "paradisescore": 152,
                        "state": "TN",
                        "statename": "Tennessee           ",
                        "pubcnt": "1882",
                        "prvcnt": "315",
                        "avestratio": 14.78,
                        "studentteacherscore": 18,
                        "prvschoolscore": 31,
                        "publicschoolscore": 36,
                        "violentcomprat": 0.279,
                        "propcomprat": 1.5619,
                        "violentscore": 8,
                        "propcrimescore": 21,
                        "sumcum": 17.44,
                        "maxcum": 29.87,
                        "mincum": 4.56,
                        "mortalityscore": 10,
                        "evtsum": 23,
                        "injsum": 440,
                        "fatsum": 91,
                        "evtscore": 11,
                        "injscore": 6,
                        "fatscore": 11
                    },
                    {
                        "paradisescore": 144,
                        "state": "NV",
                        "statename": "Nevada              ",
                        "pubcnt": "703",
                        "prvcnt": "79",
                        "avestratio": 20.34,
                        "studentteacherscore": 2,
                        "prvschoolscore": 12,
                        "publicschoolscore": 17,
                        "violentcomprat": 0.2695,
                        "propcomprat": 1.6065,
                        "violentscore": 10,
                        "propcrimescore": 16,
                        "sumcum": -7.59,
                        "maxcum": 7.59,
                        "mincum": -21.36,
                        "mortalityscore": 41,
                        "evtsum": 24,
                        "injsum": 55,
                        "fatsum": 232,
                        "evtscore": 10,
                        "injscore": 32,
                        "fatscore": 4
                    },
                    {
                        "paradisescore": 134,
                        "state": "OK",
                        "statename": "Oklahoma            ",
                        "pubcnt": "1864",
                        "prvcnt": "110",
                        "avestratio": 17.57,
                        "studentteacherscore": 6,
                        "prvschoolscore": 18,
                        "publicschoolscore": 35,
                        "violentcomprat": 0.2196,
                        "propcomprat": 1.6586,
                        "violentscore": 20,
                        "propcrimescore": 12,
                        "sumcum": 29.08,
                        "maxcum": 43.92,
                        "mincum": 13.12,
                        "mortalityscore": 2,
                        "evtsum": 24,
                        "injsum": 465,
                        "fatsum": 31,
                        "evtscore": 10,
                        "injscore": 5,
                        "fatscore": 26
                    },
                    {
                        "paradisescore": 121,
                        "state": "LA",
                        "statename": "Louisiana           ",
                        "pubcnt": "1384",
                        "prvcnt": "299",
                        "avestratio": 17.15,
                        "studentteacherscore": 7,
                        "prvschoolscore": 30,
                        "publicschoolscore": 29,
                        "violentcomprat": 0.3043,
                        "propcomprat": 1.8231,
                        "violentscore": 5,
                        "propcrimescore": 7,
                        "sumcum": 26,
                        "maxcum": 40.3,
                        "mincum": 10.54,
                        "mortalityscore": 6,
                        "evtsum": 27,
                        "injsum": 103,
                        "fatsum": 103,
                        "evtscore": 7,
                        "injscore": 20,
                        "fatscore": 10
                    }
                ]
            }
        }
    }
};

const VRRooms = {
    "Georgia": ["Atlanta","https://hubs.mozilla.com/LegVjmz/smart-scientific-dominion"],
    "California": ["LA", "https://hubs.mozilla.com/zBMziJA/teeming-rapid-safari"],
    "Florida": ["Miami", "https://hubs.mozilla.com/Dr3tuZY/quirky-pristine-soiree" ],
    "Texas": ["Dallas", "https://hubs.mozilla.com/aDjSX6R/productive-grandiose-place"]
}

function compare( a, b ) {
    if ( a.paradisescore > b.paradisescore ){
      return -1;
    }
    if ( a.paradisescore < b.paradisescore ){
      return 1;
    }
    return 0;
  }

//imitates an API call using fetch
function fetchData(params) {
    let states = json.fetchparadise3Response.Results["Result 1"]["Row"].length;
    console.log(states)
    let newJson = json.fetchparadise3Response.Results["Result 1"]["Row"];

    let g = params

    for (let i = 0; i < states; i++) {
        
        let jsonObj = json.fetchparadise3Response.Results["Result 1"]["Row"][i];
        let score = (jsonObj.evtscore * g.environment) + (jsonObj.fatscore* g.environment) + (jsonObj.mortalityscore*g.health)
         + (jsonObj.propcrimescore*g.safety) + (jsonObj.violentscore*g.safety) + jsonObj.studentteacherscore * g.education
         + jsonObj.injscore*g.environment + jsonObj.publicschoolscore*g.education + jsonObj.prvschoolscore*g.education

        newJson[i].paradisescore = score;
        newJson[i].statename= newJson[i].statename.trimEnd();
    }

    newJson.sort(compare)

    const obj = newJson[0];

    if (VRRooms[obj.statename]!=null) {
        obj.vrlink = VRRooms[obj.statename][1];
        obj.city = VRRooms[obj.statename][0];
    }

    return obj;
}

export default fetchData;